# Generated by Django 3.2.19 on 2023-10-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='property_metal',
            new_name='property_metal_list',
        ),
    ]
