# Generated by Django 3.2.19 on 2023-10-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_property_metal_product_property_metal_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='property_metal_list',
            new_name='product_metal_list',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='property_shape',
            new_name='product_shape',
        ),
    ]
